<a href="https://colab.research.google.com/github/sunyingjian/study-tensorflow/blob/master/eager%E6%A8%A1%E5%BC%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#引入Google drive文件
import os
from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/My Drive/dataset"
os.chdir(path)
os.listdir(path)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


['2_class', 'dc_2000']

In [2]:
#标准开场
%tensorflow_version 2.x
import tensorflow as tf
print('tensorflow:',format(tf.__version__))
tf.config.list_physical_devices('GPU')
tf.test.is_gpu_available()
import numpy as np
from tensorflow import keras
import glob
from tensorflow.keras import layers
import matplotlib.pyplot as plt
%matplotlib inline
tf.executing_eagerly()#判断是否处于eager模式

TensorFlow 2.x selected.
tensorflow: 2.1.0
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [3]:
#这里定义了一个x的向量
#我们用numpy中矩阵乘法运算
x=[[2,]]
m=tf.matmul(x,x)
print(m)
m.numpy()

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


array([[4]], dtype=int32)

In [4]:
#用python控制流实现tf运算
num=tf.convert_to_tensor(10)
#上面就是把一个值转换成一个向量对象
num
#输出这些值
#这样的化下面输出的就是num中的对应的numpy的值
for i in range(num.numpy()):
  i=tf.constant(i)
  if int(i%2)==0:
#这里直接转换成了python对象
    print('偶数')
  else:
    print('奇数')

偶数
奇数
偶数
奇数
偶数
奇数
偶数
奇数
偶数
奇数


In [5]:
#测试numpy中array
d=np.array([[5,6],[7,8]])
d
g=tf.convert_to_tensor(10)
g
g.numpy()

10

In [6]:
#创建变量
v=tf.Variable(0.0)
v=v+1
v.numpy()

1.0

In [7]:
v.shape

TensorShape([])

In [0]:
w=tf.Variable([[1.0]])
with tf.GradientTape() as t:
  #这里就是在这个通过记录一个过程来求导
  #这个gradient这个函数会自动追踪这个变化
  loss=w*w

In [9]:
grad = t.gradient(loss,w)
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

#常量求微分

In [0]:
a=tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
  #因为他这里是一个常量所以添加一步
  t.watch(a)
  y=a*a
  z=y*y

In [21]:
dy_da=t.gradient(y,a)
#这就是计算y对a的微分
#就是对y求导
dy_da

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [23]:
dz_da=t.gradient(z,a)
dz_da

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>

#自定义循环与训练